- name: add a gpg key for VSCode
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: add a repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  become: yes 

- name: Install apt-transport-https to access https repository
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: apt update
  apt:
    update_cache: yes
  become: yes

- name: Install VSCode
  apt:
    name: code
    state: latest
  become: yes

